skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
cpmm_t3 = "H2x2uMrSpkaPgkDViEwMiJ2JkmTsuxXqoEtsz2Recf21"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test -- --nocapture"

[hooks]
